### PR TITLE
Materials for Stockholm workshop: basic julia and TSA

### PR DESCRIPTION
**Pull request by Datseris**
cc @kahaaga

### CODE REVIEW

**Comment by Datseris** [comment]
@kahaaga I am struggling to find good examples and exercises for the ComplexityMeasures section. I thought one good example would be a sliding window applied over a timeseries to detect regime shifts. But the example timeseries I am using for it isn't particularly good; as you can see in the plot permutation entropy doesn't really perform much better than just calculating the standard deviation.

Another example I thought was timeseries classification, i.e., a'la standandard physiological timeseries application when one hopes to cluster timeseries by e.g., age or whatever using permutation entropy. But I have no data for that either.

**Comment by kahaaga** [comment]
I'll talk to some coworkers tomorrow and see if I can get my hands on some interesting data. We should have plenty of oceanographic timeseries where there are clear regime shifts. 

Regarding physiological timeseries, have you checked physionet? They have a lot of measurements of physiological parameters.

**Comment by kahaaga** [comment]
>  I thought one good example would be a sliding window applied over a timeseries to detect regime shifts

@Datseris I've experimented with some sliding window analyses on a bunch of timeseries from Physionet, particularly on timeseries of epileptic seizure episodes. However, I have the same experience as you: the standard deviation may at first glance be just as good for detecting that "something happens". 

I'm trying to find some climatic time series that may be better examples.

**Comment by Datseris** [comment]
@kahaaga don't worry about these exercises at the moment. Please focus on the example for the transfer entropy and the causal graph, as this is something you have much more expertise than me. I will try to take care of the complexity exercises now!

**Comment by kahaaga** [comment]
> don't worry about these exercises at the moment. Please focus on the example for the transfer entropy and the causal graph, as this is something you have much more expertise than me. I will try to take care of the complexity exercises now!

Ok, sure thing!

**Comment by Datseris** [comment]
@kahaaga have you had any progress on the example for the causality tools part of the workshop so far?

@ikottlarz has helped me fin some data for an exercise/application of classificaiton, heart beat timeseries of normal and abnormal heartbeat; she has e.g., computed the permutation entropy of all 10_000 timeseries to get 

image

I want to compute a "differentiability metric" for each estimator, permentropy, std, etc., . I think, the differentiability metric will just be the Kullback–Leibler divergence of the two distributions. Do we have code that calculates KL in causality tools? Actually, I am searching what is the latest version of the docs I should be reading and reviewing. Is it the docs that are built here https://github.com/JuliaDynamics/CausalityTools.jl/pull/186 ? (because last update was three days ago)

**Comment by Datseris** [comment]
If we had a cross entropy function it would be rather trivial to compute the KLdivergence, but maybe we should directly export a KLdivergence function since once one has the contigency matrix it is easy to compute it?

**Comment by kahaaga** [comment]
> have you had any progress on the example for the causality tools part of the workshop so far?

Yes, I've started working on it. I thin the example should be ready tomorrow afternoon. 

>  Do we have code that calculates KL in causality tools?

No, there is no KL divergence in https://github.com/JuliaDynamics/CausalityTools.jl/pull/186 presently. I've got a suite of various divergences implemented (Shannon/Renyi/Tsallis), but I've purposefully left them out, so that there won't be too much to review. But it's quick to get in again if it is useful for the workshop.

> but maybe we should directly export a KLdivergence function since once one has the contigency matrix it is easy to compute it?

Provided that the contingency matrix is computed such that both input variables have the same outcome space, then it is trivial to compute the KL divergence. But right now the non-observed outcomes are dropped in the contingency matrix. If the KL divergence is to be constructed from the contingency matrix, `ContingencyMatrix` must have a constructor that explicitly gives all possible outcomes (which must be the same for each dimension), and order them identically along each dimension.

However, we can, for the purpose of the workshop, just create a function `kl_divergence(p::Probabilities, q::Probabilities)` and enforce `length(p) == length(q)`. I assume you already have the probabilities in the example above?

>  Is it the docs that are built here https://github.com/JuliaDynamics/CausalityTools.jl/pull/186

Yes, that is correct. I haven't pushed my latest changes yet. I'm finishing up the bootstrap based hypothesis test for transfer entropy today, and then I'm basically done. But you can have a look already and o have a look at the overall picture

**Comment by Datseris** [comment]
> But right now the non-observed outcomes are dropped in the contingency matrix

Hm, I suspected that this would have been a problem... in principle this just comes down to that in general 0 probabilities are dropped by most estimators like `ValueHistogram` or `SymbolicPermutation`, right? But still, wouldn't it be okay if I just create 
```
est = ValueHistogram(FixedRectangularBinning(..))
c = contigency_matrix(est, x, y)
```
? Is there a quick way to get the KL-divergence from that `c`? If not, I'll just hard code a function calculates the KLdivergence for a fixed-binning-histogram for the workshop.

It's okay that you've left it out of the PR for review.

**Comment by kahaaga** [comment]
> But right now the non-observed outcomes are dropped in the contingency matrix
> Hm, I suspected that this would have been a problem.


Having zero-probability outcomes in the contingency matrix can be useful for some things, so it should definitely be in there in the future.

However, I purposefully left it out of the `ContingencyMatrix` stuff in this round because we should jointly decide on its design. There's quite a bit of subjectivity going into it. Currently, the contingency matrix basically emulates the `table` function in `R` (but without explicit row/column headers, because we don't need them for the average quantities we compute in CausalityTools). 

> But still, wouldn't it be okay if I just create [example]

Sorry, not at the moment. Quote from the source code: "The frequency matrix dimensions are dictated by the number of unique occurring values". Example:

```julia
julia> c = contingency_matrix(ValueHistogram(FixedRectangularBinning(0, 1, 2)), [0.3, 0.8], [0.3, 0.35])
2×1 ContingencyMatrix{Float64, 2, Int64}:
 0.5
 0.5
 ```
 
This is essentially the normalized version of the following frequency table:

```julia
          [0, 0.5) 
  [0, 0.5)   1
  [0.5, 1)    1
```
Since `0.5, 1)` is not visited by the second variable, it is dropped from the columns of `c`. If you can guarantee that all bins are visited by both input variables, then it'll be fine, but otherwise, the KL divergence won't be well-defined, because both input distributions must have the same length (outcome space).

**Comment by kahaaga** [comment]
>  If not, I'll just hard code a function calculates the KLdivergence for a fixed-binning-histogram for the workshop.

Yes, this is the way to go. I don't want to complicate https://juliadynamics.github.io/CausalityTools.jl/previews/PR186/independence/ further before we agree on a basic version of the information API.

**Comment by Datseris** [comment]
yes, all of this is to be visited after the workshop.

**Comment by kahaaga** [comment]
> in principle this just comes down to that in general 0 probabilities are dropped by most estimators like ValueHistogram or SymbolicPermutation

Actually, the reason `ContingencyMatrix` drops the nonobserved outcomes is that it reduced complexity when implementing it. There is no reason it *has* to, I think.

**Comment by kahaaga** [comment]
@Datseris For the transfer entropy example/exercise, is the plan to stay away from mentioning delay embeddings entirely (i.e. just use standard embedding parameters, with the joint embedding `target(t+1), target(t), source(t)`)?

**Comment by Datseris** [comment]
Yes, there is no time to go into optimizing the parameters of algorithms. I also plan to showcase the mutual information test for correlation between timeseries from CausalityTools but for this I'll just ge tthe example for my book so that is easy

**Comment by kahaaga** [comment]
> Yes, there is no time to go into optimizing the parameters of algorithms. I also plan to showcase the mutual information test for correlation between timeseries from CausalityTools but for this I'll just ge tthe example for my book so that is easy

Ok. I'm struggling a bit to construct an example that behaves like we wanted without any embedding optimization. But whatever, we just provide some time series with a ground truth (causal graph), and let people deduce a (nonoptimized) TE-based causal graph and compare it.

**Comment by Datseris** [comment]
Oh, no, sorry I wasn't clear. There is no time to teach optimizng parameters. You can use any parameters that give good results of course. I also give the transfer entropy formuyla with full delay dimension and time. Its just that we don't have time to teach "how to find gbest delay times". If you have them, uise them.

**Comment by kahaaga** [comment]
> Oh, no, sorry I wasn't clear. There is no time to teach optimizng parameters. You can use any parameters that give good results of course. I also give the transfer entropy formuyla with full delay dimension and time. Its just that we don't have time to teach "how to find gbest delay times". If you have them, uise them.

Ok, so just providing a function that finds best parameters should be fine? Alternatively, I can just make a simple wrapper that ships with CausalityTools that does the embedding optimization using the "traditional" optimized delay embedding approach.

**Comment by Datseris** [comment]
> Ok, so just providing a function that finds best parameters should be fine? 

This is fine!

**Comment by kahaaga** [comment]
> This is fine!

Ok, I'll make this part of CausalityTools, because it's nice to have anyways.

**Comment by kahaaga** [comment]
@Datseris The more I think about this exercise, the more I tend towards using a pairwise bivariate analysis to construct a causal graph. There are so many nuances to how conditioning affects the results, when it comes to confounding variables, unobserved causes etc, that it just becomes messy. You already mention this complexity in your recent update of the notebook. 

I propose just providing three time series, on which the attendees can perform a pairwise transfer entropy analysis (no conditioning), with a surrogate test for significance. Then they can compare that with what they would obtain by just looking at e.g. correlation or mutual information alone.

Given the time constraints, this should be plenty.

**Comment by Datseris** [comment]
yes I agree

**Comment by kahaaga** [comment]
> yes I agree

Ok, good. I have to call it a night now, but I'll continue this first thing in the morning. Is it possible for me to add stuff directly to the notebook, or shall I send it to you in other channels?

**Comment by Datseris** [comment]
simplest to just paste the code here. jupyter sucks for proper diffs. I'll put our names in the top of the workshop anyways.

**Comment by kahaaga** [comment]
@Datseris Here's a rough outline for the transfer entropy exercise. This should be more than enough for the given time slot, if not too much. I don't know the assumed programming knowledge of the participants, so I made a rough outline to help people along and perhaps speed up the exercise.

I sent you the file `threetimeseries.csv` by email.

First some imports and a convenience function for parameter optimisation.

```julia
using CausalityTools
using TimeseriesSurrogates
using Statistics: cor, quantile
using Combinatorics: multiset_permutations
using DelayEmbeddings: delay_f1nn
```

Import and look at time series. Measurements are taken at 30-second intervals for a 24-hour period.

```julia
# Here's three time series 
ts = readdlm("threetimeseries.csv", ';')
data = Dict("x" => ts[:, 1], "y" => ts[:, 2], "z" => ts[:, 3])

# Plot them
update_theme!(resolution = (500, 350), fontsize = 16)
fig = Figure()
ax_x = Axis(fig[1, 1], ylabel = "x")
ax_y = Axis(fig[2, 1], ylabel = "y")
ax_z = Axis(fig[3, 1], ylabel = "z", xlabel = "Time")
r = 1:400
lines!(ax_x, data["x"][r], label = "x", color = :black)
lines!(ax_y, data["y"][r], label = "y", color = :red)
lines!(ax_z, data["z"][r], label = "z")
axislegend(ax)
fig
```

Screenshot 2023-01-18 at 13 37 25

## Exercise

### Raw correlations

Compute the Pearson correlation coefficient between the pairs (x, y), (y, z), (x, z) using the 
`cor` function. Based on the correlation, would you expect these time series to be influenced 
by each other? Is it possible to say so? Why / why not?

```julia
cor(data["x"], data["y"]), cor(data["x"], data["z"]), cor(data["y"], data["z"])
```
### Causal graph from transfer entropy 

Task: Infer a causal graph from the time series `x`, `y` and `z` by applying transfer entropy  to them in a pairwise manner. Use the discrete `ValueHistogram(3)` estimator. Are there any detectable directional influences between the variables?

```julia
variable_pairs = multiset_permutations(("x", "y", "z"), 2)
results_te = Dict{String, Float64}()
for (source, target) in variable_pairs
    s, t = data[source], data[target]
    est = ValueHistogram(3)
    # Shannon transfer entropy with traditional delay-embedding optimisation. 
    # Skip optimising for source time series (you don't need to understand this now). 
    embedding = optimize_marginals_te(OptimiseTraditional(), s, t; exclude_source = true)
    te = TEShannon(; embedding)
    results_te["$source → $target"] = transferentropy(te, est, s, t) 
end
results_te
```

### Eliminating non-significant links

Infer the same causal graph, but see if some edges can be eliminated by performing
a surrogate-based significance test. For transfer entropy, this can be done
by shuffling the source time series. 

A good surrogate choice is  `BlockShuffle(2, shift = true)`, which preserves short-term
correlations, but destroys any causal relationship between the source and the target.
You're free to pick any significance threshold you like. Use at least 50 surrogates.

```julia
results_surr = Dict()
nsurr = 100
for (source, target) in variable_pairs
    s, t = data[source], data[target]
    est = ValueHistogram(3)
    # Optimise transfer entropy parameters *before* computing transfer entropy on
    # surrogate data, so that we use identical parameters for real and shuffled data. 
    embedding = optimize_marginals_te(OptimiseTraditional(), s, t; exclude_source = true)
    te = TEShannon(; embedding)

    ŝ = surrogenerator(s, BlockShuffle(2, shift = true))
    te_surr = [transferentropy(te, est, ŝ(), t) for i = 1:nsurr]
    results_surr["$source → $target"] = te_surr
end
results_surr
```

Are the links you detected significant? Did the inferred causal graph change?

```julia
xmin = minimum(vcat(values(results_te)..., values(results_surr)...,))*0.95
xmax = maximum(vcat(values(results_te)..., values(results_surr)...,))*1.05
xlims = (xmin, xmax)

with_theme(theme_minimal(), resolution = (800, 400)) do
    fig = Figure()
    ax_xy = fig[1, 1] = Axis(fig; title = "x → y")
    ax_yx = fig[2, 1] = Axis(fig; title = "y → x")
    ax_xz = fig[1, 2] = Axis(fig; title = "x → z")
    ax_zx = fig[2, 2] = Axis(fig; title = "z → x")
    ax_yz = fig[1, 3] = Axis(fig; title = "y → z")
    ax_zy = fig[2, 3] = Axis(fig; title = "z → y")
    axes = (ax_xy, ax_yx, ax_xz, ax_zx, ax_yz, ax_zy)
    names = ("x → y", "y → x", "x → z", "z → x", "y → z", "z → y")
    linkxaxes!(ax_xy, ax_yx, ax_xz, ax_zx, ax_yz, ax_zy)

    α = 0.03
    for (ax, name) in zip(axes, names)
        hideydecorations!(ax)
        vlines!(ax, results_te[name], color = :black, linewidth = 3,
            label = "TE(s → t)")
        density!(ax, results_surr[name], color = (:blue, 0.3),
            label = "pdf of TE(ŝ → t)");
        vlines!(ax, quantile(results_surr[name], 1-α), 
            label = "$(ceil(Int, (1-α)*100))th percentile",
            color = :blue, linestyle = :dot, linewidth = 2)
        
    end
    fig[:, 4] = Legend(fig, ax_xy)

    return fig
end
```

Screenshot 2023-01-18 at 13 36 55


## Some notes

- Transfer entropy is just one method for detecting directional influences from time series.
- The pairwise analysis you did here is as naive as possible. In real applications, parameters must be tuned. 
- The choice of estimator will (sometimes strongly) affect the analysis. Here we used the naive `ValueHistogram(3)` discrete estimator. It  computes transfer entropy as a sum of four entropy terms, without any bias correction.
- `ValueHistogram(3)` uses 3 subdivisions along each dimension to construct bins. The minimum dimension of the embedding for a transfer entropy analysis is 3. Therefore, for `ValueHistogram(3)`, there are `3^3 = 27` possible bins/states which observations can occupy. What do you think happens to the reliability of the entropy estimates (and thus the transfer entropy estimate) when increasing the number of boxes? Does it increase or decrease? You can assume the number of observations and embedding dimension stays the same. 
- In real applications, you also need to do a conditional variant to account for confounding variables ("partial transfer entropy").
- Many very sophisticated and powerful methods for inferring causal graphs using conditional independence testing exist (see e.g. Runge et al.).

## Things to try

- Repeat the same analysis as above with an increasing number of  boxes, e.g. `ValueHistgram(4)`, `ValueHistogram(5)`.
- Try to repeat the exact same analysis as above, but using `Zhu1` estimator, with `k` (the number of nearest neighbors) set to about 1/40th of the length of the input data. The `Zhu1` estimator computes *continuous/differential* transfer entropy, and has built-in bias-correction.

**Comment by kahaaga** [comment]
@Datseris The relevant branch for CausalityTools is now simply called `v2`, and can be installed by the command `Pkg.add(url = "https://github.com/JuliaDynamics/CausalityTools.jl/", rev = "v2")`. The associated PR, with a documentation link, is [here](https://github.com/JuliaDynamics/CausalityTools.jl/pull/187) (the docs are still building, so not visible yet)

**Comment by kahaaga** [comment]
@Datseris I've updated the transfer entropy example above so that it is runnable. There's also some thoughts at the end, and suggestions for further exercises. 

I also updated the `threetimeseries.csv` file. I've emailed you the updated version.

Originally, I used the dedicated `Zhu1` transfer entropy estimator in the example, but I switched in to `ValueHistogram`, because the former is too slow to run in an interactive session like this. I suggested to try the `Zhu1` estimator as an exercise instead.

**Comment by Datseris** [comment]
@kahaaga could you please write down here the exact equations that generated the data? Or code if you also used an `rng`?

**Comment by kahaaga** [comment]
@Datseris Here you go

```julia
using Distributions: Normal
using Random: MersenneTwister, default_rng
function ar3(n::Int; rng = default_rng())
    x1 = zeros(n)
    x2 = zeros(n)
    x3 = zeros(n)
    
    N1 = Normal(0, 1)
    N2 = Normal(0, 1)
    N3 = Normal(0, 1)
    x1[1:3] .= rand(rng, N1, 3)
    x2[1:3] .= rand(rng, N2, 3)
    x3[1:3] .= rand(rng, N3, 3)

    for i = 4:n
        x1[i] = 0.6*sqrt(2)*x1[i-1] - 0.71*x1[i-2] + rand(rng, N1)
        x2[i] = 0.7*x1[i-2] + 0.71*x2[i-2] + rand(rng, N2)
        x3[i] = 0.67*x3[i-2] - 0.6*x2[i-1] - 0.2*x3[i-3] + rand(rng, N3)
    end
    return x1, x2, x3
end

rng = MersenneTwister(1234)
x, y, z = ar3(2*60*24; rng)
data = [x y z]
using DelimitedFiles
writedlm("threetimeseries.csv", data, ";")
```

**Comment by Datseris** [comment]
i just pushed the finished workshop!

**Comment by kahaaga** [comment]
@Datseris And I just finished reading through it. Looks great! You did a nice job converting the transfer entropy example into something more lecture-like that is easy to follow.

**Pull request merged**
